- name: Configure cluster common parts
  hosts:
    - masters
    - nodes
    - etcd
    - lbs
    - nfsservers
  become: yes
  roles:
    - base
    - cluster_common

- name: Configure openshift VMs
  hosts:
    - masters
    - nodes
    - lbs
  become: yes
  roles:
    - role: lvm_storage

    - role: docker_host
      docker_lvol_size: "50%FREE"
      docker_lvol_vg_name: "vg_data"

- name: Configure openshift masters
  hosts:
    - masters
  become: yes
  roles:
    - cluster_master
    - openshift_master

- name: Prepare nfs server for OpenShift NFS playbook
  hosts:
    - nfsservers
  become: yes
  roles:
    - role: lvm_storage

- name: Run OpenShift installation
  include: ../../../openshift-ansible/playbooks/byo/config.yml

- name: Copy custom templates to master-1
  hosts: masters[0]
  tasks:
    - name: copy default project template
      template:
        src: templates/project-request.yaml
        dest: /home/cloud-user/project-request.yaml
